// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: monitoring.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoringService_Login_FullMethodName                  = "/monitoring.MonitoringService/Login"
	MonitoringService_CreateNotification_FullMethodName     = "/monitoring.MonitoringService/CreateNotification"
	MonitoringService_GetNotification_FullMethodName        = "/monitoring.MonitoringService/GetNotification"
	MonitoringService_ListNotifications_FullMethodName      = "/monitoring.MonitoringService/ListNotifications"
	MonitoringService_CreateSentNotification_FullMethodName = "/monitoring.MonitoringService/CreateSentNotification"
	MonitoringService_GetSentNotification_FullMethodName    = "/monitoring.MonitoringService/GetSentNotification"
	MonitoringService_ListSentNotifications_FullMethodName  = "/monitoring.MonitoringService/ListSentNotifications"
	MonitoringService_CreateService_FullMethodName          = "/monitoring.MonitoringService/CreateService"
	MonitoringService_GetService_FullMethodName             = "/monitoring.MonitoringService/GetService"
	MonitoringService_ListServices_FullMethodName           = "/monitoring.MonitoringService/ListServices"
	MonitoringService_CreateResult_FullMethodName           = "/monitoring.MonitoringService/CreateResult"
	MonitoringService_GetResult_FullMethodName              = "/monitoring.MonitoringService/GetResult"
	MonitoringService_ListResults_FullMethodName            = "/monitoring.MonitoringService/ListResults"
	MonitoringService_SendNotification_FullMethodName       = "/monitoring.MonitoringService/SendNotification"
	MonitoringService_BatchSend_FullMethodName              = "/monitoring.MonitoringService/BatchSend"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Единый сервис мониторинга
type MonitoringServiceClient interface {
	// Аутентификация
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Notification методы (CRUD)
	CreateNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*NotificationResponse, error)
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*Notification, error)
	ListNotifications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NotificationList, error)
	// SentNotification методы (CRUD)
	CreateSentNotification(ctx context.Context, in *SentNotification, opts ...grpc.CallOption) (*SentNotificationResponse, error)
	GetSentNotification(ctx context.Context, in *GetSentNotificationRequest, opts ...grpc.CallOption) (*SentNotification, error)
	ListSentNotifications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SentNotificationList, error)
	// Service методы (CRUD)
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error)
	ListServices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceList, error)
	// Result методы (CRUD)
	CreateResult(ctx context.Context, in *Result, opts ...grpc.CallOption) (*ResultResponse, error)
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*Result, error)
	ListResults(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultList, error)
	// Операции отправки уведомлений
	SendNotification(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*BatchSendResponse, error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, MonitoringService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) CreateNotification(ctx context.Context, in *Notification, opts ...grpc.CallOption) (*NotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, MonitoringService_CreateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*Notification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Notification)
	err := c.cc.Invoke(ctx, MonitoringService_GetNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) ListNotifications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NotificationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotificationList)
	err := c.cc.Invoke(ctx, MonitoringService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) CreateSentNotification(ctx context.Context, in *SentNotification, opts ...grpc.CallOption) (*SentNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentNotificationResponse)
	err := c.cc.Invoke(ctx, MonitoringService_CreateSentNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetSentNotification(ctx context.Context, in *GetSentNotificationRequest, opts ...grpc.CallOption) (*SentNotification, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentNotification)
	err := c.cc.Invoke(ctx, MonitoringService_GetSentNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) ListSentNotifications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SentNotificationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentNotificationList)
	err := c.cc.Invoke(ctx, MonitoringService_ListSentNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, MonitoringService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, MonitoringService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) ListServices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, MonitoringService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) CreateResult(ctx context.Context, in *Result, opts ...grpc.CallOption) (*ResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, MonitoringService_CreateResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, MonitoringService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) ListResults(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ResultList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultList)
	err := c.cc.Invoke(ctx, MonitoringService_ListResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) SendNotification(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, MonitoringService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*BatchSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSendResponse)
	err := c.cc.Invoke(ctx, MonitoringService_BatchSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility.
//
// Единый сервис мониторинга
type MonitoringServiceServer interface {
	// Аутентификация
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Notification методы (CRUD)
	CreateNotification(context.Context, *Notification) (*NotificationResponse, error)
	GetNotification(context.Context, *GetNotificationRequest) (*Notification, error)
	ListNotifications(context.Context, *emptypb.Empty) (*NotificationList, error)
	// SentNotification методы (CRUD)
	CreateSentNotification(context.Context, *SentNotification) (*SentNotificationResponse, error)
	GetSentNotification(context.Context, *GetSentNotificationRequest) (*SentNotification, error)
	ListSentNotifications(context.Context, *emptypb.Empty) (*SentNotificationList, error)
	// Service методы (CRUD)
	CreateService(context.Context, *Service) (*ServiceResponse, error)
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	ListServices(context.Context, *emptypb.Empty) (*ServiceList, error)
	// Result методы (CRUD)
	CreateResult(context.Context, *Result) (*ResultResponse, error)
	GetResult(context.Context, *GetResultRequest) (*Result, error)
	ListResults(context.Context, *emptypb.Empty) (*ResultList, error)
	// Операции отправки уведомлений
	SendNotification(context.Context, *SendRequest) (*SendResponse, error)
	BatchSend(context.Context, *BatchSendRequest) (*BatchSendResponse, error)
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMonitoringServiceServer) CreateNotification(context.Context, *Notification) (*NotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedMonitoringServiceServer) GetNotification(context.Context, *GetNotificationRequest) (*Notification, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedMonitoringServiceServer) ListNotifications(context.Context, *emptypb.Empty) (*NotificationList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedMonitoringServiceServer) CreateSentNotification(context.Context, *SentNotification) (*SentNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSentNotification not implemented")
}
func (UnimplementedMonitoringServiceServer) GetSentNotification(context.Context, *GetSentNotificationRequest) (*SentNotification, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSentNotification not implemented")
}
func (UnimplementedMonitoringServiceServer) ListSentNotifications(context.Context, *emptypb.Empty) (*SentNotificationList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSentNotifications not implemented")
}
func (UnimplementedMonitoringServiceServer) CreateService(context.Context, *Service) (*ServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedMonitoringServiceServer) GetService(context.Context, *GetServiceRequest) (*Service, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedMonitoringServiceServer) ListServices(context.Context, *emptypb.Empty) (*ServiceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedMonitoringServiceServer) CreateResult(context.Context, *Result) (*ResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResult not implemented")
}
func (UnimplementedMonitoringServiceServer) GetResult(context.Context, *GetResultRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedMonitoringServiceServer) ListResults(context.Context, *emptypb.Empty) (*ResultList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResults not implemented")
}
func (UnimplementedMonitoringServiceServer) SendNotification(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedMonitoringServiceServer) BatchSend(context.Context, *BatchSendRequest) (*BatchSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSend not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}
func (UnimplementedMonitoringServiceServer) testEmbeddedByValue()                           {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	// If the following call panics, it indicates UnimplementedMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).CreateNotification(ctx, req.(*Notification))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).ListNotifications(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_CreateSentNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SentNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).CreateSentNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_CreateSentNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).CreateSentNotification(ctx, req.(*SentNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetSentNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSentNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetSentNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetSentNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetSentNotification(ctx, req.(*GetSentNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_ListSentNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).ListSentNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_ListSentNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).ListSentNotifications(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).CreateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).ListServices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_CreateResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).CreateResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_CreateResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).CreateResult(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_ListResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).ListResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_ListResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).ListResults(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).SendNotification(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_BatchSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).BatchSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_BatchSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).BatchSend(ctx, req.(*BatchSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MonitoringService_Login_Handler,
		},
		{
			MethodName: "CreateNotification",
			Handler:    _MonitoringService_CreateNotification_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _MonitoringService_GetNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _MonitoringService_ListNotifications_Handler,
		},
		{
			MethodName: "CreateSentNotification",
			Handler:    _MonitoringService_CreateSentNotification_Handler,
		},
		{
			MethodName: "GetSentNotification",
			Handler:    _MonitoringService_GetSentNotification_Handler,
		},
		{
			MethodName: "ListSentNotifications",
			Handler:    _MonitoringService_ListSentNotifications_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _MonitoringService_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _MonitoringService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _MonitoringService_ListServices_Handler,
		},
		{
			MethodName: "CreateResult",
			Handler:    _MonitoringService_CreateResult_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _MonitoringService_GetResult_Handler,
		},
		{
			MethodName: "ListResults",
			Handler:    _MonitoringService_ListResults_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _MonitoringService_SendNotification_Handler,
		},
		{
			MethodName: "BatchSend",
			Handler:    _MonitoringService_BatchSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitoring.proto",
}
