// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: monitoring.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения для аутентификации
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

// Notification сообщения
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Notification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Notification          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationResponse) GetData() *Notification {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type NotificationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationList) Reset() {
	*x = NotificationList{}
	mi := &file_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationList) ProtoMessage() {}

func (x *NotificationList) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationList.ProtoReflect.Descriptor instead.
func (*NotificationList) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationList) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NotificationList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SentNotification сообщения
type SentNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentNotification) Reset() {
	*x = SentNotification{}
	mi := &file_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentNotification) ProtoMessage() {}

func (x *SentNotification) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentNotification.ProtoReflect.Descriptor instead.
func (*SentNotification) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *SentNotification) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SentNotification) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type SentNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SentNotification      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentNotificationResponse) Reset() {
	*x = SentNotificationResponse{}
	mi := &file_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentNotificationResponse) ProtoMessage() {}

func (x *SentNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentNotificationResponse.ProtoReflect.Descriptor instead.
func (*SentNotificationResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *SentNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SentNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SentNotificationResponse) GetData() *SentNotification {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSentNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSentNotificationRequest) Reset() {
	*x = GetSentNotificationRequest{}
	mi := &file_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSentNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSentNotificationRequest) ProtoMessage() {}

func (x *GetSentNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSentNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetSentNotificationRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *GetSentNotificationRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type SentNotificationList struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SentNotifications []*SentNotification    `protobuf:"bytes,1,rep,name=sent_notifications,json=sentNotifications,proto3" json:"sent_notifications,omitempty"`
	Count             int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SentNotificationList) Reset() {
	*x = SentNotificationList{}
	mi := &file_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentNotificationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentNotificationList) ProtoMessage() {}

func (x *SentNotificationList) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentNotificationList.ProtoReflect.Descriptor instead.
func (*SentNotificationList) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *SentNotificationList) GetSentNotifications() []*SentNotification {
	if x != nil {
		return x.SentNotifications
	}
	return nil
}

func (x *SentNotificationList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Service сообщения
type Service struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tenant         string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	DeprecatedDate string                 `protobuf:"bytes,4,opt,name=deprecated_date,json=deprecatedDate,proto3" json:"deprecated_date,omitempty"`
	BusinessLine   string                 `protobuf:"bytes,5,opt,name=business_line,json=businessLine,proto3" json:"business_line,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Service) GetDeprecatedDate() string {
	if x != nil {
		return x.DeprecatedDate
	}
	return ""
}

func (x *Service) GetBusinessLine() string {
	if x != nil {
		return x.BusinessLine
	}
	return ""
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Service               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_monitoring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceResponse) GetData() *Service {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_monitoring_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{12}
}

func (x *GetServiceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_monitoring_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceList) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServiceList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Result сообщения
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_monitoring_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{14}
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Result) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Result                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_monitoring_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{15}
}

func (x *ResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResultResponse) GetData() *Result {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_monitoring_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{16}
}

func (x *GetResultRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResultList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultList) Reset() {
	*x = ResultList{}
	mi := &file_monitoring_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultList) ProtoMessage() {}

func (x *ResultList) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultList.ProtoReflect.Descriptor instead.
func (*ResultList) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{17}
}

func (x *ResultList) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ResultList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Сообщения для отправки уведомлений
type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_monitoring_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{18}
}

func (x *SendRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_monitoring_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{19}
}

func (x *SendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type BatchSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SendRequest         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	IntervalMs    int32                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	Workers       int32                  `protobuf:"varint,3,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendRequest) Reset() {
	*x = BatchSendRequest{}
	mi := &file_monitoring_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendRequest) ProtoMessage() {}

func (x *BatchSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendRequest.ProtoReflect.Descriptor instead.
func (*BatchSendRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{20}
}

func (x *BatchSendRequest) GetMessages() []*SendRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BatchSendRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *BatchSendRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type BatchSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,4,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendResponse) Reset() {
	*x = BatchSendResponse{}
	mi := &file_monitoring_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendResponse) ProtoMessage() {}

func (x *BatchSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendResponse.ProtoReflect.Descriptor instead.
func (*BatchSendResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{21}
}

func (x *BatchSendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchSendResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchSendResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchSendResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_monitoring_proto protoreflect.FileDescriptor

const file_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x10monitoring.proto\x12\n" +
	"monitoring\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"c\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\";\n" +
	"\fNotification\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"x\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.monitoring.NotificationR\x04data\"1\n" +
	"\x16GetNotificationRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"h\n" +
	"\x10NotificationList\x12>\n" +
	"\rnotifications\x18\x01 \x03(\v2\x18.monitoring.NotificationR\rnotifications\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"J\n" +
	"\x10SentNotification\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\"\x80\x01\n" +
	"\x18SentNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1c.monitoring.SentNotificationR\x04data\";\n" +
	"\x1aGetSentNotificationRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"y\n" +
	"\x14SentNotificationList\x12K\n" +
	"\x12sent_notifications\x18\x01 \x03(\v2\x1c.monitoring.SentNotificationR\x11sentNotifications\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x93\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12'\n" +
	"\x0fdeprecated_date\x18\x04 \x01(\tR\x0edeprecatedDate\x12#\n" +
	"\rbusiness_line\x18\x05 \x01(\tR\fbusinessLine\"n\n" +
	"\x0fServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.monitoring.ServiceR\x04data\"#\n" +
	"\x11GetServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"T\n" +
	"\vServiceList\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.monitoring.ServiceR\bservices\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"D\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\"l\n" +
	"\x0eResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.monitoring.ResultR\x04data\"\"\n" +
	"\x10GetResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"P\n" +
	"\n" +
	"ResultList\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.monitoring.ResultR\aresults\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\":\n" +
	"\vSendRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"z\n" +
	"\fSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\"\x82\x01\n" +
	"\x10BatchSendRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.monitoring.SendRequestR\bmessages\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x05R\n" +
	"intervalMs\x12\x18\n" +
	"\aworkers\x18\x03 \x01(\x05R\aworkers\"\xa3\x01\n" +
	"\x11BatchSendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12#\n" +
	"\rsuccess_count\x18\x04 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x05R\n" +
	"errorCount2\xe2\b\n" +
	"\x11MonitoringService\x12<\n" +
	"\x05Login\x12\x18.monitoring.LoginRequest\x1a\x19.monitoring.LoginResponse\x12P\n" +
	"\x12CreateNotification\x12\x18.monitoring.Notification\x1a .monitoring.NotificationResponse\x12O\n" +
	"\x0fGetNotification\x12\".monitoring.GetNotificationRequest\x1a\x18.monitoring.Notification\x12I\n" +
	"\x11ListNotifications\x12\x16.google.protobuf.Empty\x1a\x1c.monitoring.NotificationList\x12\\\n" +
	"\x16CreateSentNotification\x12\x1c.monitoring.SentNotification\x1a$.monitoring.SentNotificationResponse\x12[\n" +
	"\x13GetSentNotification\x12&.monitoring.GetSentNotificationRequest\x1a\x1c.monitoring.SentNotification\x12Q\n" +
	"\x15ListSentNotifications\x12\x16.google.protobuf.Empty\x1a .monitoring.SentNotificationList\x12A\n" +
	"\rCreateService\x12\x13.monitoring.Service\x1a\x1b.monitoring.ServiceResponse\x12@\n" +
	"\n" +
	"GetService\x12\x1d.monitoring.GetServiceRequest\x1a\x13.monitoring.Service\x12?\n" +
	"\fListServices\x12\x16.google.protobuf.Empty\x1a\x17.monitoring.ServiceList\x12>\n" +
	"\fCreateResult\x12\x12.monitoring.Result\x1a\x1a.monitoring.ResultResponse\x12=\n" +
	"\tGetResult\x12\x1c.monitoring.GetResultRequest\x1a\x12.monitoring.Result\x12=\n" +
	"\vListResults\x12\x16.google.protobuf.Empty\x1a\x16.monitoring.ResultList\x12E\n" +
	"\x10SendNotification\x12\x17.monitoring.SendRequest\x1a\x18.monitoring.SendResponse\x12H\n" +
	"\tBatchSend\x12\x1c.monitoring.BatchSendRequest\x1a\x1d.monitoring.BatchSendResponseB4Z2github.com/mdemidenko/monitoring-platform/pkg/grpcb\x06proto3"

var (
	file_monitoring_proto_rawDescOnce sync.Once
	file_monitoring_proto_rawDescData []byte
)

func file_monitoring_proto_rawDescGZIP() []byte {
	file_monitoring_proto_rawDescOnce.Do(func() {
		file_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)))
	})
	return file_monitoring_proto_rawDescData
}

var file_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_monitoring_proto_goTypes = []any{
	(*LoginRequest)(nil),               // 0: monitoring.LoginRequest
	(*LoginResponse)(nil),              // 1: monitoring.LoginResponse
	(*Notification)(nil),               // 2: monitoring.Notification
	(*NotificationResponse)(nil),       // 3: monitoring.NotificationResponse
	(*GetNotificationRequest)(nil),     // 4: monitoring.GetNotificationRequest
	(*NotificationList)(nil),           // 5: monitoring.NotificationList
	(*SentNotification)(nil),           // 6: monitoring.SentNotification
	(*SentNotificationResponse)(nil),   // 7: monitoring.SentNotificationResponse
	(*GetSentNotificationRequest)(nil), // 8: monitoring.GetSentNotificationRequest
	(*SentNotificationList)(nil),       // 9: monitoring.SentNotificationList
	(*Service)(nil),                    // 10: monitoring.Service
	(*ServiceResponse)(nil),            // 11: monitoring.ServiceResponse
	(*GetServiceRequest)(nil),          // 12: monitoring.GetServiceRequest
	(*ServiceList)(nil),                // 13: monitoring.ServiceList
	(*Result)(nil),                     // 14: monitoring.Result
	(*ResultResponse)(nil),             // 15: monitoring.ResultResponse
	(*GetResultRequest)(nil),           // 16: monitoring.GetResultRequest
	(*ResultList)(nil),                 // 17: monitoring.ResultList
	(*SendRequest)(nil),                // 18: monitoring.SendRequest
	(*SendResponse)(nil),               // 19: monitoring.SendResponse
	(*BatchSendRequest)(nil),           // 20: monitoring.BatchSendRequest
	(*BatchSendResponse)(nil),          // 21: monitoring.BatchSendResponse
	(*emptypb.Empty)(nil),              // 22: google.protobuf.Empty
}
var file_monitoring_proto_depIdxs = []int32{
	2,  // 0: monitoring.NotificationResponse.data:type_name -> monitoring.Notification
	2,  // 1: monitoring.NotificationList.notifications:type_name -> monitoring.Notification
	6,  // 2: monitoring.SentNotificationResponse.data:type_name -> monitoring.SentNotification
	6,  // 3: monitoring.SentNotificationList.sent_notifications:type_name -> monitoring.SentNotification
	10, // 4: monitoring.ServiceResponse.data:type_name -> monitoring.Service
	10, // 5: monitoring.ServiceList.services:type_name -> monitoring.Service
	14, // 6: monitoring.ResultResponse.data:type_name -> monitoring.Result
	14, // 7: monitoring.ResultList.results:type_name -> monitoring.Result
	18, // 8: monitoring.BatchSendRequest.messages:type_name -> monitoring.SendRequest
	0,  // 9: monitoring.MonitoringService.Login:input_type -> monitoring.LoginRequest
	2,  // 10: monitoring.MonitoringService.CreateNotification:input_type -> monitoring.Notification
	4,  // 11: monitoring.MonitoringService.GetNotification:input_type -> monitoring.GetNotificationRequest
	22, // 12: monitoring.MonitoringService.ListNotifications:input_type -> google.protobuf.Empty
	6,  // 13: monitoring.MonitoringService.CreateSentNotification:input_type -> monitoring.SentNotification
	8,  // 14: monitoring.MonitoringService.GetSentNotification:input_type -> monitoring.GetSentNotificationRequest
	22, // 15: monitoring.MonitoringService.ListSentNotifications:input_type -> google.protobuf.Empty
	10, // 16: monitoring.MonitoringService.CreateService:input_type -> monitoring.Service
	12, // 17: monitoring.MonitoringService.GetService:input_type -> monitoring.GetServiceRequest
	22, // 18: monitoring.MonitoringService.ListServices:input_type -> google.protobuf.Empty
	14, // 19: monitoring.MonitoringService.CreateResult:input_type -> monitoring.Result
	16, // 20: monitoring.MonitoringService.GetResult:input_type -> monitoring.GetResultRequest
	22, // 21: monitoring.MonitoringService.ListResults:input_type -> google.protobuf.Empty
	18, // 22: monitoring.MonitoringService.SendNotification:input_type -> monitoring.SendRequest
	20, // 23: monitoring.MonitoringService.BatchSend:input_type -> monitoring.BatchSendRequest
	1,  // 24: monitoring.MonitoringService.Login:output_type -> monitoring.LoginResponse
	3,  // 25: monitoring.MonitoringService.CreateNotification:output_type -> monitoring.NotificationResponse
	2,  // 26: monitoring.MonitoringService.GetNotification:output_type -> monitoring.Notification
	5,  // 27: monitoring.MonitoringService.ListNotifications:output_type -> monitoring.NotificationList
	7,  // 28: monitoring.MonitoringService.CreateSentNotification:output_type -> monitoring.SentNotificationResponse
	6,  // 29: monitoring.MonitoringService.GetSentNotification:output_type -> monitoring.SentNotification
	9,  // 30: monitoring.MonitoringService.ListSentNotifications:output_type -> monitoring.SentNotificationList
	11, // 31: monitoring.MonitoringService.CreateService:output_type -> monitoring.ServiceResponse
	10, // 32: monitoring.MonitoringService.GetService:output_type -> monitoring.Service
	13, // 33: monitoring.MonitoringService.ListServices:output_type -> monitoring.ServiceList
	15, // 34: monitoring.MonitoringService.CreateResult:output_type -> monitoring.ResultResponse
	14, // 35: monitoring.MonitoringService.GetResult:output_type -> monitoring.Result
	17, // 36: monitoring.MonitoringService.ListResults:output_type -> monitoring.ResultList
	19, // 37: monitoring.MonitoringService.SendNotification:output_type -> monitoring.SendResponse
	21, // 38: monitoring.MonitoringService.BatchSend:output_type -> monitoring.BatchSendResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_monitoring_proto_init() }
func file_monitoring_proto_init() {
	if File_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitoring_proto_goTypes,
		DependencyIndexes: file_monitoring_proto_depIdxs,
		MessageInfos:      file_monitoring_proto_msgTypes,
	}.Build()
	File_monitoring_proto = out.File
	file_monitoring_proto_goTypes = nil
	file_monitoring_proto_depIdxs = nil
}
