// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/batch": {
            "post": {
                "description": "Отправляет несколько сообщений с возможностью настройки интервалов между отправками и количества параллельных воркеров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Пакетная отправка уведомлений",
                "parameters": [
                    {
                        "description": "Данные для пакетной отправки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пакетная обработка завершена",
                        "schema": {
                            "$ref": "#/definitions/api.BatchResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Проверяет доступность сервиса и всех зависимых компонентов (Telegram API, хранилище)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка состояния сервиса",
                "responses": {
                    "200": {
                        "description": "Сервис работает корректно",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Сервис недоступен",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications": {
            "get": {
                "description": "Возвращает список всех уведомлений, которые были созданы для отправки (включая неотправленные)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Получение списка всех созданных уведомлений",
                "responses": {
                    "200": {
                        "description": "Список уведомлений",
                        "schema": {
                            "$ref": "#/definitions/api.NotificationsResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications/sent": {
            "get": {
                "description": "Возвращает список уведомлений, которые были успешно отправлены в Telegram",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Получение списка отправленных уведомлений",
                "responses": {
                    "200": {
                        "description": "Список отправленных уведомлений",
                        "schema": {
                            "$ref": "#/definitions/api.SentNotificationsResponse"
                        }
                    }
                }
            }
        },
        "/api/send": {
            "post": {
                "description": "Отправляет одно сообщение в указанный чат Telegram. Если chat_id не указан, используется чат из конфигурации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Отправка одного уведомления",
                "parameters": [
                    {
                        "description": "Данные для отправки уведомления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Уведомление успешно отправлено",
                        "schema": {
                            "$ref": "#/definitions/api.SendResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные запроса",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка отправки уведомления",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/status": {
            "get": {
                "description": "Возвращает текущее состояние сервиса, статистику отправленных уведомлений и конфигурационные параметры",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Получение статуса и статистики сервиса",
                "responses": {
                    "200": {
                        "description": "Статус сервиса",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BatchMessage": {
            "description": "Сообщение в составе пакетного запроса",
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "chat_id": {
                    "description": "ID чата Telegram (опционально)",
                    "type": "string",
                    "example": "123456789"
                },
                "text": {
                    "description": "Текст сообщения для отправки",
                    "type": "string",
                    "minLength": 1,
                    "example": "Тестовое сообщение 1"
                }
            }
        },
        "api.BatchRequest": {
            "description": "Запрос на пакетную отправку уведомлений с настройками интервалов и параллелизма",
            "type": "object",
            "required": [
                "messages"
            ],
            "properties": {
                "interval_ms": {
                    "description": "Интервал между отправками сообщений в миллисекундах (опционально)",
                    "type": "integer",
                    "example": 1000
                },
                "messages": {
                    "description": "Список сообщений для отправки",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/api.BatchMessage"
                    }
                },
                "workers": {
                    "description": "Количество параллельных воркеров для отправки (опционально, от 1 до 10)",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "api.BatchResponse": {
            "description": "Ответ при выполнении пакетной отправки уведомлений",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные о результате обработки",
                    "type": "object",
                    "properties": {
                        "error_count": {
                            "description": "Количество сообщений с ошибкой отправки",
                            "type": "integer",
                            "example": 2
                        },
                        "interval_ms": {
                            "description": "Использованный интервал между отправками в мс",
                            "type": "integer",
                            "example": 2000
                        },
                        "success_count": {
                            "description": "Количество успешно отправленных сообщений",
                            "type": "integer",
                            "example": 8
                        },
                        "total": {
                            "description": "Общее количество обработанных сообщений",
                            "type": "integer",
                            "example": 10
                        },
                        "workers": {
                            "description": "Количество использованных воркеров",
                            "type": "integer",
                            "example": 2
                        }
                    }
                },
                "message": {
                    "description": "Сообщение о результате",
                    "type": "string",
                    "example": "Batch processing completed"
                },
                "success": {
                    "description": "Флаг успешного выполнения",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.ErrorResponse": {
            "description": "Стандартный ответ при возникновении ошибки",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Описание ошибки",
                    "type": "string",
                    "example": "Invalid request: text is required"
                },
                "success": {
                    "description": "Флаг успешного выполнения (всегда false)",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "api.HealthResponse": {
            "description": "Ответ сервиса на запрос проверки состояния",
            "type": "object",
            "properties": {
                "app": {
                    "description": "Название приложения",
                    "type": "string",
                    "example": "monitoring-platform"
                },
                "status": {
                    "description": "Статус сервиса",
                    "type": "string",
                    "example": "ok"
                },
                "storage": {
                    "description": "Статистика хранилища",
                    "type": "object",
                    "properties": {
                        "notifications": {
                            "description": "Количество созданных уведомлений",
                            "type": "integer",
                            "example": 10
                        },
                        "sent_notifications": {
                            "description": "Количество отправленных уведомлений",
                            "type": "integer",
                            "example": 8
                        }
                    }
                },
                "timestamp": {
                    "description": "Временная метка ответа",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "version": {
                    "description": "Версия приложения",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.NotificationItem": {
            "description": "Элемент уведомления в списке",
            "type": "object",
            "properties": {
                "chat_id": {
                    "description": "ID чата",
                    "type": "string",
                    "example": "123456789"
                },
                "text": {
                    "description": "Текст уведомления",
                    "type": "string",
                    "example": "Тестовое сообщение"
                }
            }
        },
        "api.NotificationsResponse": {
            "description": "Ответ со списком всех созданных уведомлений",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные со списком уведомлений",
                    "type": "object",
                    "properties": {
                        "count": {
                            "description": "Общее количество уведомлений",
                            "type": "integer",
                            "example": 5
                        },
                        "notifications": {
                            "description": "Список уведомлений",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.NotificationItem"
                            }
                        }
                    }
                },
                "success": {
                    "description": "Флаг успешного выполнения",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SendRequest": {
            "description": "Запрос на отправку одного уведомления",
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "chat_id": {
                    "description": "ID чата Telegram (опционально, если не указан - используется из конфигурации)",
                    "type": "string",
                    "example": "123456789"
                },
                "text": {
                    "description": "Текст сообщения для отправки (обязательное поле)",
                    "type": "string",
                    "minLength": 1,
                    "example": "Привет, это тестовое сообщение!"
                }
            }
        },
        "api.SendResponse": {
            "description": "Ответ при успешной отправке уведомления",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные об отправленном уведомлении",
                    "type": "object",
                    "properties": {
                        "chat_id": {
                            "description": "ID чата, куда отправлено сообщение",
                            "type": "string",
                            "example": "123456789"
                        },
                        "message_id": {
                            "description": "ID сообщения в Telegram (если отправка успешна)",
                            "type": "integer",
                            "example": 123
                        },
                        "text": {
                            "description": "Текст отправленного сообщения",
                            "type": "string",
                            "example": "Тестовое сообщение"
                        }
                    }
                },
                "message": {
                    "description": "Сообщение о результате",
                    "type": "string",
                    "example": "Notification sent successfully"
                },
                "success": {
                    "description": "Флаг успешного выполнения",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.SentNotificationItem": {
            "description": "Элемент отправленного уведомления в списке",
            "type": "object",
            "properties": {
                "chat_id": {
                    "description": "ID чата",
                    "type": "integer",
                    "example": 123456789
                },
                "message_id": {
                    "description": "ID сообщения в Telegram",
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "api.SentNotificationsResponse": {
            "description": "Ответ со списком отправленных уведомлений",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные со списком отправленных уведомлений",
                    "type": "object",
                    "properties": {
                        "count": {
                            "description": "Общее количество отправленных уведомлений",
                            "type": "integer",
                            "example": 3
                        },
                        "sent_notifications": {
                            "description": "Список отправленных уведомлений",
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SentNotificationItem"
                            }
                        }
                    }
                },
                "success": {
                    "description": "Флаг успешного выполнения",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.StatusResponse": {
            "description": "Ответ с текущим статусом и статистикой сервиса",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Данные о статусе сервиса",
                    "type": "object",
                    "properties": {
                        "config": {
                            "description": "Конфигурационные параметры",
                            "type": "object",
                            "properties": {
                                "app_name": {
                                    "description": "Название приложения",
                                    "type": "string",
                                    "example": "monitoring-platform"
                                },
                                "app_version": {
                                    "description": "Версия приложения",
                                    "type": "string",
                                    "example": "1.0.0"
                                },
                                "environment": {
                                    "description": "Окружение выполнения",
                                    "type": "string",
                                    "example": "development"
                                }
                            }
                        },
                        "stats": {
                            "description": "Статистика сервиса",
                            "type": "object",
                            "properties": {
                                "pending_notifications": {
                                    "description": "Количество ожидающих отправки уведомлений",
                                    "type": "integer",
                                    "example": 3
                                },
                                "total_notifications": {
                                    "description": "Всего созданных уведомлений",
                                    "type": "integer",
                                    "example": 15
                                },
                                "total_sent_notifications": {
                                    "description": "Всего отправленных уведомлений",
                                    "type": "integer",
                                    "example": 12
                                }
                            }
                        },
                        "status": {
                            "description": "Текущий статус сервиса",
                            "type": "string",
                            "example": "running"
                        },
                        "timestamp": {
                            "description": "Временная метка",
                            "type": "string",
                            "example": "2024-01-01T12:00:00Z"
                        }
                    }
                },
                "success": {
                    "description": "Флаг успешного выполнения",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Monitoring Platform API",
	Description:      "API для отправки уведомлений через Telegram",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
